
export type TheoryConcept={name:string;formula:string;explain:string};
export type TheoryDomain={
 id:string;n:string;level:string;title:string;aim:string;core:string;
 concepts:TheoryConcept[];bass:string;trap:string;proof:string;
};
export type TheoryRow={name:string;formula:string;meaning:string;semitones?:number};
export type TheoryDictionary={id:string;title:string;intro:string;columns:[string,string,string];rows:TheoryRow[]};

export const THEORY_DOMAINS:TheoryDomain[]=[
 {id:"notation",n:"01",level:"FOUNDATION",title:"Notation, symbols & musical language",aim:"Read what another musician means without guessing.",core:"Notation separates pitch, duration, articulation, dynamics and navigation. A bassist must read bass clef and chord symbols, understand rhythmic notation before pitch, and know when two written names describe the same sounding fret but a different harmonic job.",concepts:[
  {name:"Staff, bass clef & register",formula:"LINES G–B–D–F–A · SPACES A–C–E–G",explain:"Clef assigns pitch to staff positions; ledger lines extend the range. Octave placement matters because the same pitch class can support, crowd or dominate the ensemble in different registers."},
  {name:"Accidentals, key signatures & spelling",formula:"♯ RAISES · ♭ LOWERS · ♮ CANCELS",explain:"C♯ and D♭ can share a fret, but spelling shows direction and chord function. Write one letter per scale degree and preserve the chord’s thirds so the harmony remains readable."},
  {name:"Note values, rests, ties & dots",formula:"WHOLE 4 · HALF 2 · QUARTER 1 · EIGHTH ½ · 16TH ¼",explain:"A tie adds durations across beats; a dot adds half the written value; a rest is measured time, not absence of responsibility. Count the full grid even when no note sounds."},
  {name:"Articulation, dynamics & road signs",formula:"LEGATO · STACCATO · ACCENT · p–f · D.S. · D.C. · CODA",explain:"Length, accent and volume can change a bass line more than pitch. Repeats, endings, segno and coda define the route; missing one can destroy the form while every note remains correct."},
 ],bass:"Read rhythm first, mark section boundaries, circle accidentals and decide the octave before playing. TAB can show location, but only notation and chord symbols explain duration, function and ensemble intent.",trap:"Decoding one note at a time and stopping at mistakes. Reading is continuous prediction: eyes ahead, pulse alive, recovery at the next musical checkpoint.",proof:"Sight-read 16 unfamiliar bars in bass clef, count every rest, follow all repeats and explain each accidental and chord symbol afterward."},

 {id:"rhythm",n:"02",level:"FOUNDATION",title:"Pulse, subdivision, feel & syncopation",aim:"Know exactly where a note lives in time—and why it feels good there.",core:"Bass joins rhythm to harmony. Tempo is the speed of the reference pulse; subdivision is the internal grid; feel is how attacks and lengths sit around that grid. Strong time continues through rests, fills, accents and disappearing clicks.",concepts:[
  {name:"Pulse, tempo & internal clock",formula:"BPM = BEATS PER MINUTE",explain:"The pulse is the recurring reference; tempo only measures its rate. Internal time means the body predicts the next pulse without chasing an external click."},
  {name:"Subdivision hierarchy",formula:"¼ → ⅛ → 16TH · TRIPLET → ⅛-TRIPLET → 12/8",explain:"Every attack and rest belongs to a smaller grid. Count or vocalize the smallest active subdivision so syncopation remains deliberate rather than approximate."},
  {name:"Syncopation & anticipation",formula:"ACCENT OFFBEAT · TIE ACROSS STRONG BEAT · ATTACK BEFORE CHANGE",explain:"Syncopation shifts expected weight; anticipation states the next harmony early. The effect works only if the listener still feels the unplayed strong beat underneath."},
  {name:"Feel, placement & note length",formula:"AHEAD · CENTRED · BEHIND · SHORT · CONNECTED",explain:"Micro-placement and duration shape pocket. Playing behind is not being late, and short is not rushed: both require a stable shared grid and repeatable control."},
 ],bass:"Lock the bass attack to the drummer’s chosen reference—often kick, hi-hat subdivision or snare backbeat—then control note endings so the groove breathes. Rests and releases are part of the line.",trap:"Practising only attacks. A line can land on time and still feel bad because releases, accents and subdivision are inconsistent.",proof:"Play one groove through four bars of click and four silent bars, return with the click three times, then reproduce centred, ahead and behind feels without changing tempo."},

 {id:"meter",n:"03",level:"INTERMEDIATE → ADVANCED",title:"Meter, tuplets, polyrhythm & metric control",aim:"Feel complex rhythm as organized cycles, not mathematical panic.",core:"Meter groups pulses; beat division decides whether it is simple or compound. Additive meters combine short groups, tuplets divide space unusually, polyrhythms overlay different equal cycles and polymeters align different bar lengths. Metric modulation makes one subdivision become the new pulse.",concepts:[
  {name:"Simple, compound & swing",formula:"4/4 = 4×2 · 6/8 = 2×3 · SWING = UNEQUAL 8TH FEEL",explain:"Top number counts written units, but felt beats may differ. Compound meter groups eighths in threes; swing shades paired eighths without requiring a rigid triplet ratio."},
  {name:"Odd and additive meters",formula:"5 = 3+2 / 2+3 · 7 = 2+2+3 / 3+2+2",explain:"Group the bar by recurring accents instead of counting a long number string. A bass ostinato should make the grouping obvious to the band and audience."},
  {name:"Tuplets, hemiola & displacement",formula:"3:2 · 5:4 · 3 GROUPS ACROSS 2 BARS",explain:"Tuplets fit a chosen number of equal events into another value. Hemiola changes perceived grouping; displacement moves a motif while preserving its internal rhythm."},
  {name:"Polyrhythm, polymeter & metric modulation",formula:"3:2 · 4/4 OVER 3/4 · OLD ⅛-TRIPLET = NEW ⅛",explain:"Polyrhythm shares a span with different subdivisions; polymeter shares tempo with different bar cycles. Metric modulation preserves a mathematical subdivision relationship while redefining the beat."},
 ],bass:"Reduce every complex meter to a vocal pattern, accent map and repeating low-register cell. Make the form audible before adding fills or harmonic movement.",trap:"Counting successfully while the groove has no hierarchy. Mathematics is only useful when accents, phrase length and return points can be heard.",proof:"Clap and play 5/4 in two groupings, 7/8 in three groupings, a 3:2 polyrhythm and one metric modulation, then re-enter beat 1 without a visual counter."},

 {id:"form",n:"04",level:"ALL LEVELS",title:"Form, phrases, charts & navigation",aim:"Always know where the music is, what changed and what returns next.",core:"Form organizes time above the bar: motives become phrases, phrases become sections and sections create a complete arc. Harmonic rhythm is the rate of chord change. A professional bassist tracks section length, cues, repeats, endings, pickups, tags, vamps and dynamics while preserving the groove.",concepts:[
  {name:"Motif, phrase, period & cadence",formula:"IDEA → QUESTION → ANSWER → ARRIVAL",explain:"A motif is a reusable identity; a phrase carries it toward punctuation; a period pairs question and answer. Cadence closes or suspends the thought."},
  {name:"Common song forms",formula:"VERSE–CHORUS · AABA · 12-BAR BLUES · THROUGH-COMPOSED",explain:"Form labels describe relationships, not fixed instrumentation. Count actual bars and note altered repeats, pre-choruses, post-choruses, interludes, tags and codas."},
  {name:"Harmonic rhythm & phrase rhythm",formula:"CHANGES PER BAR · PHRASE LENGTH 2/4/8/16",explain:"Chord-change rate creates momentum independently of tempo. Phrase rhythm tells when ideas begin, repeat, extend or overlap section boundaries."},
  {name:"Lead sheets, road maps & cues",formula:"INTRO · A · B · SOLO · SHOUT · OUTRO",explain:"A useful chart states key, meter, tempo, bars, chords, hits, rests and navigation. Cues are musical events—lyric, fill, melody or gesture—not only page numbers."},
 ],bass:"Memorize each section’s first root, length, last-bar cue and dynamic job. If lost, keep pulse, simplify to the tonal centre and recover at the next unmistakable section boundary.",trap:"Knowing the chord loop but not the song. A bassist can repeat correct harmony and still miss the bridge, stop, breakdown or final ending.",proof:"Hear an unfamiliar song twice, write a bar-accurate road map with cues, then perform the form without looking away from the band."},

 {id:"fretboard",n:"05",level:"FOUNDATION → AUTOMATIC",title:"Fretboard, tuning, intervals & transposition",aim:"See function everywhere instead of memorizing isolated boxes.",core:"The fretboard is a repeating pitch grid shaped by tuning. Intervals describe distance and function independent of key; transposition preserves relationships while changing absolute pitch. Register, string choice and position change tone and physical phrasing even when the notes are identical.",concepts:[
  {name:"Pitch class, octave & register",formula:"12 PITCH CLASSES · FRET 12 = OCTAVE",explain:"All Cs share pitch class but not frequency or ensemble role. Register controls weight, clarity, masking and perceived tension."},
  {name:"Interval number and quality",formula:"COUNT LETTERS + COUNT SEMITONES",explain:"Number comes from letter distance; quality comes from semitones. Perfect families use perfect/augmented/diminished; major families use major/minor plus altered forms."},
  {name:"Inversions and compound intervals",formula:"NUMBERS SUM TO 9 · QUALITIES INVERT",explain:"2↔7, 3↔6 and 4↔5. A tenth is a third plus an octave; compound intervals spread harmony while retaining its function."},
  {name:"Tuning geometry and transposition",formula:"E–A–D–G = PERFECT 4THS · SAME INTERVALS, NEW ROOT",explain:"Standard tuning repeats shapes predictably except across range limits. Drop, five- and six-string tunings change available register, not interval theory; recalculate from each open string."},
 ],bass:"Name every note, degree and interval from the current root; find it on all strings in two registers; then move the whole relationship to a random key without changing fingering logic or rhythmic identity.",trap:"Knowing one shape and calling it fretboard knowledge. Real command survives a new string, octave, key, direction, tuning and starting finger.",proof:"From five random roots, name and play every interval within two seconds below fret 7 and above fret 12, then transpose one bass line through all 12 keys."},

 {id:"scales",n:"06",level:"FOUNDATION → ADVANCED",title:"Keys, scales, modes & tonal collections",aim:"Understand what a collection sounds like, how it is spelled and when it applies.",core:"A scale orders pitches around a centre; a key also implies hierarchy and harmonic behavior. Scale formulas are interval maps, not fingering commands. Major and minor systems, pentatonics, blues, modes, chromatic and symmetric collections each offer different degrees of stability and colour.",concepts:[
  {name:"Major and the three minor forms",formula:"MAJOR 1 2 3 4 5 6 7 · NAT MIN ♭3 ♭6 ♭7 · HARM MIN 7 · MEL MIN 6 7",explain:"Natural minor supplies the key collection; harmonic minor strengthens dominant pull; melodic minor smooths the raised 6–7 ascent and becomes a modern chord-scale source."},
  {name:"Pentatonic and blues language",formula:"MAJ PENT 1 2 3 5 6 · MIN PENT 1 ♭3 4 5 ♭7 · BLUES + ♭5",explain:"Removing semitone friction creates portable, open vocabulary. The blues note is expressive motion, not a pitch that must be held or tempered identically in every style."},
  {name:"Modes and characteristic degrees",formula:"PARALLEL COMPARISON AROUND ONE ROOT",explain:"Hear each mode against the same tonic and compare the one or two degrees that change its gravity. Parent-scale derivation explains spelling; parallel sound explains music."},
  {name:"Chromatic, whole-tone, diminished & synthetic scales",formula:"12-TONE · 6 EQUAL WHOLE STEPS · H–W / W–H",explain:"Symmetric scales reduce a unique tonic and serve specific dominant or diminished colors. Synthetic collections are valid only when their interval identity and harmonic context are audible."},
 ],bass:"For every scale, sing 1 and the defining degrees, spell it correctly, map it in two regions, build its chords and create a groove with no more than five pitches before running the full shape.",trap:"Treating a scale as a list of allowed notes. Rhythm, chord function, target, register and duration decide whether a theoretically available note works now.",proof:"Given any root and chord context, spell the relevant collection, sing its identity, locate it across the neck and make it recognizable in an original four-bar bass line."},

 {id:"chords",n:"07",level:"FOUNDATION → ADVANCED",title:"Chord construction, extensions & slash harmony",aim:"Know what every chord symbol contains, omits and asks the bass to clarify.",core:"Chords are interval structures heard simultaneously or arpeggiated. Stacking diatonic thirds creates triads, sevenths and extensions; alterations change specific degrees. Inversions and slash chords assign the bass note explicitly, so the bassist can redefine stability and motion without changing the upper voices.",concepts:[
  {name:"Triads and suspended chords",formula:"MAJ 1 3 5 · MIN 1 ♭3 5 · DIM 1 ♭3 ♭5 · AUG 1 3 ♯5 · SUS 1 4/2 5",explain:"The third defines major/minor; the fifth defines stability or alteration. Sus replaces the third and delays quality rather than adding another ordinary extension."},
  {name:"Seventh-chord families",formula:"MAJ7 · 7 · m7 · m7♭5 · dim7 · mMaj7",explain:"Third and seventh are the main guide tones. Their qualities distinguish tonic major, dominant, minor, half-diminished, fully diminished and minor-major colors."},
  {name:"Extensions, adds and alterations",formula:"9=2 · 11=4 · 13=6 · ♭9 ♯9 ♯11 ♭13",explain:"Extensions assume a seventh-chord stack unless marked add. Alterations belong to chord function and voice leading; they are tensions with destinations, not decorative spelling."},
  {name:"Inversions, slash chords & upper structures",formula:"C/E · Dm/C · G/A · TRIAD OVER BASS",explain:"A slash note is the required bass pitch, which may be an inversion, pedal or independent harmony. Upper structures describe colors above a stable bass and can imply extended or altered sonorities."},
 ],bass:"On each symbol, identify required root or slash note, third, seventh and destination. Omit low extensions that muddy the arrangement; state enough information for the harmony without competing with the keyboard or guitar.",trap:"Playing the full scale because the chord symbol looks complicated. First reduce the symbol to bass note, quality, seventh and altered destination.",proof:"Spell and arpeggiate 20 common chord symbols from random roots, name their guide tones, then choose a clean bass note and next destination in a real progression."},

 {id:"diatonic",n:"08",level:"INTERMEDIATE",title:"Diatonic harmony, numbers & key relationships",aim:"Generate the chords of any key and understand their local jobs.",core:"Diatonic harmony builds chords only from a key’s notes. Roman numerals describe scale-degree root and quality; Nashville numbers prioritize transposable roots and practical charts. Relative keys share notes, parallel keys share tonic, and borrowed chords temporarily import color from a parallel system.",concepts:[
  {name:"Key signatures and circle of fifths",formula:"CLOCKWISE +1♯ · COUNTERCLOCKWISE +1♭",explain:"The circle organizes key signatures, dominant–tonic relationships and nearby modulation options. It predicts spelling; it does not dictate which chord must come next."},{name:"The cycle is how the bass is tuned",formula:"E → A → D → G · EACH STRING A FOURTH UP",explain:"Read anticlockwise the circle of fifths is a circle of fourths, and a bass in standard tuning is four of its steps laid side by side. Moving round the cycle is therefore the same physical move each time — across one string, same fret — which is why it is the cheapest way to take any pattern through all twelve keys."},{name:"Reading a key off the cycle",formula:"LAST SHARP = 7 · LAST FLAT = 4 · SECOND-TO-LAST FLAT NAMES THE KEY",explain:"The sharps and flats of a signature appear in cycle order, so the signature names the key without any counting. The final sharp is the leading tone, a semitone under home. With two flats or more, the one before the last is the key itself; a single flat is the exception and means F."},{name:"Diatonic cycle against chromatic cycle",formula:"IN KEY: ONE STEP IS A TRITONE · CHROMATIC: EVERY STEP A PERFECT FOURTH",explain:"Run the cycle using only the notes of one key and six steps are perfect fourths while one is a tritone. In C that step is F to B — degrees 4 and 7 — and it is the same tritone that sits inside G7 and makes the dominant want to move. Run the cycle chromatically instead and every step is a perfect fourth, which is the version to practise patterns through."},
  {name:"Harmonizing the major scale",formula:"I maj7 · ii m7 · iii m7 · IV maj7 · V7 · vi m7 · viiø",explain:"Stack alternate scale degrees. The pattern transposes intact and supplies chord tones, functions and available voice-leading routes in every major key."},
  {name:"Roman numerals and Nashville numbers",formula:"QUALITY + SCALE DEGREE · 1–7 WITH ALTERATIONS",explain:"Roman case and symbols preserve analytical quality; Nashville notation communicates roots, bars, pushes and inversions quickly in sessions."},
  {name:"Relative, parallel and borrowed harmony",formula:"C MAJOR ↔ A MINOR · C MAJOR ↔ C MINOR",explain:"Relative systems share collection but not gravity. Parallel borrowing changes one or more degrees around the same tonic, creating color such as iv, ♭VI or ♭VII in major."},
 ],bass:"Reduce every progression to numbers, identify structural beats and roots, then choose when to state roots, thirds, fifths, sevenths, inversions or approaches. Numbers reveal transposition; chord tones reveal the line.",trap:"Assuming every diatonic chord has equal weight. Position in phrase, duration, melody and bass motion can make the same chord structural, passing or prolongational.",proof:"In all 12 keys, state the diatonic triads and sevenths, analyze a progression in Roman and Nashville numbers, then transpose it without rewriting shapes."},

 {id:"function",n:"09",level:"INTERMEDIATE → ADVANCED",title:"Function, cadences, tonicization & modulation",aim:"Hear why harmony moves and where it is trying to arrive.",core:"Functional harmony groups chords by behavior: tonic stability, predominant departure and dominant demand for resolution. Cadences articulate phrases. Secondary dominants briefly tonicize a target; modulation establishes a new key strongly enough that its functions and cadences replace the old centre.",concepts:[
  {name:"Tonic, predominant and dominant",formula:"T → PD → D → T",explain:"Function is behavior, not one chord name. Substitutes share important tones and directional tendencies; bass motion can strengthen or weaken the perceived function."},
  {name:"Cadence families",formula:"AUTHENTIC V–I · HALF →V · PLAGAL IV–I · DECEPTIVE V–vi",explain:"Cadences combine harmonic arrival, metric placement and melodic closure. A V–I off the phrase ending may not feel cadential at all."},
  {name:"Secondary dominants and tonicization",formula:"V/x → x · LEADING-TONE CHORD vii°/x",explain:"A chromatic dominant points to a diatonic or borrowed target. Its altered notes are locally functional, so the bass should expose destination and guide-tone motion."},
  {name:"Modulation and pivot logic",formula:"COMMON CHORD · COMMON TONE · DIRECT · SEQUENCE",explain:"A pivot can belong to both keys; direct modulation changes without one. A new key is confirmed by sustained hierarchy, dominant action, cadence and phrase-level emphasis—not one accidental."},
 ],bass:"Pre-hear the destination root and guide tones. Use stepwise, chromatic or common-tone motion to make function audible; on modulation, establish the new tonic through register, duration and arrival placement.",trap:"Calling every chromatic chord a key change or every V–I a modulation. Ask whether the new centre persists, receives its own functions and controls the phrase ending.",proof:"Analyze and play tonic–predominant–dominant routes, four cadence types, three secondary dominants and two modulation methods while naming every destination before it sounds."},

 {id:"voice",n:"10",level:"INTERMEDIATE → PROFESSIONAL",title:"Voice leading, inversions & bass motion",aim:"Connect harmony with the smallest meaningful movement.",core:"Voice leading treats each chord tone as a melodic line. Thirds and sevenths expose quality and function; common tones hold continuity; semitone and whole-step destinations create inevitability. Because the bass defines inversion, its line can smooth harmony, intensify a cadence or deliberately resist the upper voices.",concepts:[
  {name:"Guide tones and tendency tones",formula:"3RD + 7TH · 7→1 · 4→3",explain:"Guide tones identify chord family; tendency tones have strong contextual destinations. Hearing them first prevents scale choices from obscuring progression."},
  {name:"Common, contrary and oblique motion",formula:"HOLD · MOVE TOGETHER · MOVE OPPOSITE",explain:"Different motion types control independence and smoothness. Contrary motion opens texture; oblique motion preserves a pedal; similar motion can strengthen contour but risks parallel weight."},
  {name:"Inversions and linear bass",formula:"ROOT · 1ST INV 3RD · 2ND INV 5TH · 3RD INV 7TH",explain:"Inversions preserve chord identity while changing bass direction and stability. A linear bass can connect static upper harmony through scale, chromatic or patterned motion."},
  {name:"Pedal, ostinato and contrary harmony",formula:"FIXED BASS UNDER CHANGES · REPEATED CELL",explain:"A pedal makes upper chords relate to one sustained bass; an ostinato adds rhythmic identity. Both can create deliberate nonfunctional tension and slash-chord colors."},
 ],bass:"Build the destination skeleton first: required bass note, third and seventh. Connect by nearest meaningful motion, then add approaches only if the skeleton remains singable without accompaniment.",trap:"Choosing a scale for every chord before hearing the line. Harmony is often clearer from two connected guide tones than from seven available pitches.",proof:"Play a progression as roots, then inversions, guide-tone shells and one chromatic version; the chord movement must remain identifiable with no accompaniment."},

 {id:"modal",n:"11",level:"INTERMEDIATE → ADVANCED",title:"Modal, pedal & nonfunctional harmony",aim:"Develop one sound deeply without forcing dominant–tonic logic.",core:"Modal harmony establishes a tonic through repetition, duration, register and pedal rather than functional cadences. Characteristic degrees distinguish parallel modes. Chords may color one centre without demanding a new key, and planing or quartal structures can move by shape and voice rather than classical function.",concepts:[
  {name:"Parent versus parallel modes",formula:"C MAJOR MODES SHARE NOTES · C MODES SHARE TONIC",explain:"Parent thinking explains derivation; parallel comparison reveals sound. A bassist improvises more reliably by hearing degree function from the actual tonic."},
  {name:"Characteristic tones and modal cadence",formula:"DORIAN 6 · PHRYGIAN ♭2 · LYDIAN ♯4 · MIXOLYDIAN ♭7",explain:"Identity emerges when the defining degree is exposed against tonic and resolved in a characteristic phrase. Repetition without context can make it sound accidental."},
  {name:"Modal chord fields and pedal points",formula:"TONIC PEDAL + COLOR CHORDS",explain:"Upper structures can shift while bass preserves centre. Chord choice should emphasize the mode’s unique degrees and avoid accidentally importing stronger functional gravity."},
  {name:"Quartal harmony, planing & constant structure",formula:"STACK 4THS · MOVE SAME VOICING",explain:"Quartal sonorities soften major/minor identity; planing moves a voicing in parallel. Both are controlled by centre, register, contour and voice-leading context."},
 ],bass:"Establish tonic unmistakably, feature the characteristic degree without scale-running, keep a repeated rhythmic identity and treat upper chord changes as colors around home until the music proves otherwise.",trap:"Equating a mode with its parent major scale or assigning a new mode to every chord. Modal music needs one audible centre and phrase behavior, not labels alone.",proof:"Make all seven parallel modes recognizable with four or five pitches, then support a modal vamp for three minutes without losing tonic, time or motif identity."},

 {id:"bassline",n:"12",level:"ALL LEVELS",title:"Bass-line construction & ensemble function",aim:"Choose the smallest line that makes time, harmony and form undeniable.",core:"A bass line is not a scale exercise under chords. It establishes harmonic roots and inversions, locks rhythmic hierarchy, outlines form, controls energy and connects destinations. Repetition creates identity; variation creates development; register, articulation and silence decide how much space the line occupies.",concepts:[
  {name:"Role hierarchy",formula:"TIME → FORM → HARMONY → FEEL → DECORATION",explain:"If a fill damages time or form, it is too expensive. Supportive playing can be simple in pitch while sophisticated in placement, length and dynamics."},
  {name:"Structural beats and target hierarchy",formula:"ROOT/SLASH ON ARRIVAL · 3RD/7TH FOR QUALITY · 5TH FOR SUPPORT",explain:"Strong arrivals need clear harmonic evidence; weaker subdivisions carry approach, repetition or color. Context can deliberately reverse the hierarchy."},
  {name:"Approach vocabulary",formula:"DIATONIC · CHROMATIC BELOW/ABOVE · ENCLOSURE · SCALE RUN",explain:"Choose the destination first and fit the path to available time. An approach gains meaning from landing placement, not from being chromatic by itself."},
  {name:"Repetition, variation, fills and space",formula:"STATE → REPEAT → VARY ONE THING → RETURN",explain:"Change rhythm, ending, register, articulation or density one at a time. A fill should answer the song and hand the next downbeat back clearly."},
 ],bass:"Start with roots and exact note lengths against drums. Add thirds or sevenths for quality, approaches into named destinations, and fills only at phrase openings; remove anything that weakens the original pocket.",trap:"Judging a line by difficulty or note count. The real test is whether the band’s time, harmony, section and emotional direction become clearer.",proof:"Create three different lines over one progression: minimum support, stylistic pocket and melodic development. All three must preserve form and be recognizable without chordal accompaniment."},

 {id:"styles",n:"13",level:"INTERMEDIATE → PROFESSIONAL",title:"Style grammar, forms & historical vocabulary",aim:"Sound stylistically credible before adding your personal voice.",core:"Style is a system of rhythmic placement, note length, harmonic vocabulary, form, tone, articulation and ensemble interaction—not a collection of licks. Learn representative recordings, historical lineage and the drummer relationship, then separate transferable principles from artist-specific imitation.",concepts:[
  {name:"Blues, jazz and walking",formula:"12-BAR · ii–V–I · CHORD TONE ON BEAT · APPROACH NEXT ROOT",explain:"Walking balances quarter-note time, chord clarity, voice leading and melodic contour. Blues harmony mixes dominant color, call/response and flexible thirds."},
  {name:"Funk, soul, Motown and R&B",formula:"ONE · 16TH GRID · SYNCOPATION · MOTIF VARIATION",explain:"Repetition, ghost placement, anticipations and controlled chromatic approaches create forward motion. Note length and kick relationship are central style markers."},
  {name:"Rock, grunge, metal, pop and reggae",formula:"RIFF/ROOT SUPPORT · SECTION ENERGY · REGGAE SPACE/DELAY",explain:"Rock-family bass may double riffs, anchor roots or create countermelody; genre changes attack and density. Reggae often prioritizes deep placement, short harmonic vocabulary and negative space."},
  {name:"Latin, Afrobeat, electronic and progressive systems",formula:"CLAVE/TUMBAO · INTERLOCKING OSTINATI · LOOP EVOLUTION · ODD GROUPS",explain:"These broad families contain many distinct traditions. Learn the governing timeline, percussion relationship and form from authentic sources; do not reduce them to one generic pattern."},
 ],bass:"For each style, document subdivision, primary drum lock, typical note length, harmonic density, form, common approaches and three reference players. Reproduce the grammar, then create a new line without copying a recording.",trap:"Using tone or technique as the whole style: fuzz does not create grunge, slap does not create funk and roots alone do not create reggae.",proof:"Perform the same progression convincingly in six contrasting styles; a listener should identify each from time feel, articulation and line design before hearing the tone preset."},

 {id:"improv",n:"14",level:"INTERMEDIATE → ADVANCED",title:"Improvisation, melody & motivic development",aim:"Create a coherent statement instead of reciting available material.",core:"Improvisation organizes melody, rhythm, harmony, form and color in real time. Chord tones provide structure, target notes create direction, motifs provide identity, and phrasing provides speech. Vocabulary becomes personal only when it can be heard first, transformed and placed deliberately.",concepts:[
  {name:"Targets, chord tones and available tensions",formula:"DESTINATION FIRST · PATH SECOND",explain:"Choose an arrival note, beat and duration before decoration. Tensions are judged by local chord, style and resolution—not by a universal avoid-note list."},
  {name:"Motif and transformation",formula:"REPEAT · SEQUENCE · INVERT · RETROGRADE · DISPLACE · ALTER END",explain:"Preserve enough rhythm or contour for recognition while changing one parameter. Development creates memory and direction with fewer notes."},
  {name:"Phrase, breath and conversation",formula:"CALL · SPACE · ANSWER · EXTEND · CLOSE",explain:"Phrase length and silence shape meaning. An answer can imitate, contrast, complete or interrupt the call; continuous sound removes punctuation."},
  {name:"Arc, density, register and climax",formula:"ESTABLISH → DEVELOP → DESTABILIZE → PEAK → RETURN",explain:"Long-form improvisation distributes tension across time. A unique climax requires earlier restraint and a final return in harmony, rhythm, register and density."},
 ],bass:"Sing the next target, limit the pitch set, repeat one rhythmic identity and leave intentional space. Increase vocabulary only when time, form and destination stay audible.",trap:"Confusing spontaneity with randomness or skill with density. A scale run can be correct and still say nothing; one developed note can define the entire solo.",proof:"Improvise three minutes using one motif, a five-pitch limit, at least 25% silence and one climax; afterward sing the motif and explain every structural arrival."},

 {id:"outside",n:"15",level:"ADVANCED",title:"Chromaticism, outside playing & controlled resolution",aim:"Create friction that the listener can follow—and resolve it on command.",core:"Outside sound is a relationship to an established inside reference. Chromatic approaches decorate targets; enclosures surround them; side-slipping displaces a recognizable idea; superimposition temporarily creates another structure. Duration, accent, register and landing beat determine perceived distance as much as pitch.",concepts:[
  {name:"Passing, neighbour and approach tones",formula:"STRUCTURE → PATH → STRUCTURE",explain:"A passing tone connects two destinations; a neighbour leaves and returns; an approach points into one target. Metric placement tells the ear which note is structural."},
  {name:"Enclosures and chromatic cells",formula:"ABOVE–BELOW–TARGET · BELOW–ABOVE–TARGET",explain:"Surround a pre-heard chord tone and land it with structural weight. Vary order, width and rhythm without losing the destination."},
  {name:"Side-slip and superimposition",formula:"MOTIF ±1 SEMITONE · TRIAD/PENTATONIC OVER CHORD",explain:"Side-slip preserves idea identity while moving its centre. Superimposition overlays a chosen structure whose tensions must be named and resolved."},
  {name:"Altered dominant and symmetric tension",formula:"ALT: 1 ♭9 ♯9 3 ♭5 ♭13 ♭7 · DIM / WHOLE-TONE",explain:"Altered, diminished and whole-tone sounds are strongest when guide tones and destinations remain explicit. Maximum tension without directed motion becomes static noise."},
 ],bass:"State home first, name the outside device, duration and landing note, keep the original groove and reproduce the same departure–return effect three times before making it longer.",trap:"Selecting exotic notes first and searching for a rescue afterward. The destination, beat and amount of friction must exist before departure.",proof:"Record 12 named departures using four devices; every return lands on its planned beat and chord tone, time never changes and each effect is reproducible three times."},

 {id:"advanced-harmony",n:"16",level:"ADVANCED → EXPERT",title:"Substitution, reharmonization & modern harmony",aim:"Change harmony while preserving—or deliberately changing—the song’s logic.",core:"Reharmonization changes the chords beneath a melody or form. Substitutions work through shared function, guide tones, bass motion or symmetry. Advanced color includes tritone and backdoor dominants, diminished connectors, modal interchange, constant structures, upper-structure triads, intervallic harmony and polytonal layers.",concepts:[
  {name:"Functional substitutions",formula:"iii/vi FOR I · ii/IV FOR PD · vii°/V FOR D",explain:"Chords can substitute when they share function and important tones. The melody and bass determine whether the replacement feels smooth, surprising or incorrect."},
  {name:"Tritone, backdoor and diminished routes",formula:"♭II7→I · ♭VII7→I · vii° CONNECTORS",explain:"Tritone dominants share the 3rd/7th pair with V7; backdoor motion approaches tonic through borrowed color; diminished chords connect targets by semitone and symmetry."},
  {name:"Modal interchange and constant structures",formula:"BORROW FROM PARALLEL · MOVE SAME QUALITY",explain:"Borrowed chords retain one tonic while changing modal color. Constant structures move the same chord type through non-diatonic roots and rely on contour, common tones or bass logic."},
  {name:"Upper structures, intervallic and polytonal color",formula:"TRIAD OVER CHORD · FIXED INTERVAL SET · TWO CENTRES",explain:"Upper structures organize extensions; intervallic cells avoid scalar gravity; polytonality layers identifiable centres. These devices need clear register and reference to remain readable."},
 ],bass:"Protect melody, form and destination first. Test the original roots, then guide tones, then the proposed bass motion; a reharmonization is valid when its new tension and release are audible, not merely nameable.",trap:"Using advanced chord names as proof of musical value. If the melody clashes unintentionally, bass motion loses direction or form becomes unclear, the theory has not served the song.",proof:"Reharmonize one eight-bar melody three ways—functional, modal and chromatic—then explain every retained melody tone, bass destination and tension–release decision."},

 {id:"ear",n:"17",level:"ALL LEVELS · NEVER FINISHED",title:"Ear training, transcription, acoustics & global systems",aim:"Hear theory before naming it and respect systems that Western notation cannot fully describe.",core:"Ear training connects sound to label, notation and instrument: audiation, intervals, scale degrees, bass lines, chords, function, rhythm and form. Acoustics explains overtone, timbre, phase, register and intonation. Twelve-tone equal temperament is one tuning system; maqam, raga, tala, clave and African timeline traditions organize pitch and time through culture-specific behavior that cannot be reduced to a generic scale.",concepts:[
  {name:"Audiation and functional hearing",formula:"IMAGINE → SING → FIND → VERIFY",explain:"Audiation predicts sound without the instrument. Functional hearing identifies degree relative to a centre, which transfers better than memorizing isolated interval songs."},
  {name:"Transcription and analysis workflow",formula:"FORM → RHYTHM → ROOTS → PITCH → ARTICULATION → THEORY",explain:"Slow only when necessary. Loop short phrases, sing before locating, verify at full tempo and write enough detail to reproduce feel—not only fret numbers."},
  {name:"Overtones, timbre, phase and intonation",formula:"FUNDAMENTAL + PARTIALS · FREQUENCY RATIO",explain:"Tone changes which partials dominate; low frequencies need space and stable phase relationships. Intonation depends on context, attack, sustain, ensemble and tuning system—not a tuner light alone."},
  {name:"Temperament and culture-specific pitch/time",formula:"12-TET ≠ UNIVERSAL · AJNAS/SAYR · RAGA · TALA · CLAVE/TIMELINE",explain:"Notation is an approximation of living practice. Learn intonation, ornament, cadence, timeline and phrase grammar by listening, copying repertoire and studying qualified tradition-bearers."},
 ],bass:"Transcribe complete bass behavior: pitch, rhythm, duration, articulation, dynamics, form, drum relationship and tone. Sing every target and compare your recorded take to the source at full tempo.",trap:"Naming sounds without reproducing them, or treating a tuner and Western scale formula as universal truth. Recognition must become voice, fretboard and musical behavior.",proof:"Transcribe one complete verse and chorus by ear, perform it with matching feel, explain its harmony and form, then sing and play every structural target without the recording."},

 {id:"arranging",n:"18",level:"PROFESSIONAL INTEGRATION",title:"Composition, arranging & professional application",aim:"Use theory to make the whole piece clearer—not just the bass part busier.",core:"Composition shapes motive, melody, harmony, rhythm, form, texture and tension. Arranging assigns those roles across instruments and registers. The bass may support, counter, pedal, double, reharmonize or lead; the correct choice depends on melody, kick, low-frequency space, section energy and production intent.",concepts:[
  {name:"Melody, counterpoint and bass relationship",formula:"SUPPORT · DOUBLE · CONTRARY · CALL/ANSWER · PEDAL",explain:"Independent lines need rhythmic and registral separation plus controlled consonance/dissonance. The bass can answer melody without stealing its arrival points."},
  {name:"Register, texture, doubling and low-end space",formula:"ONE CLEAR LOWEST FUNCTION",explain:"Closely spaced low notes create masking and roughness. Decide who owns sub, bass motion and low chord extensions; move other information upward or thin it."},
  {name:"Development, contrast and large-scale tension",formula:"REPEAT · VARY · CONTRAST · RECAPITULATE",explain:"Sections need related identity and different function. Arrange density, register, harmony and rhythm so the climax is prepared and the return has meaning."},
  {name:"Charts, transposition, rehearsal and production decisions",formula:"KEY · TEMPO · METER · FORM · HITS · DYNAMICS · PATCH",explain:"Professional theory becomes clear communication: readable charts, number systems, cue language, range awareness and versions. Record decisions so live, rehearsal and studio arrangements remain consistent."},
 ],bass:"Before writing, define the song’s emotional arc and each section’s bass job. Draft roots and rhythm, test against melody and kick, then add counterpoint, fills, reharmonization or effects only where the arrangement has space.",trap:"Optimizing the bass part in isolation. A brilliant line that masks melody, fights the kick, removes contrast or confuses form is a weak arrangement choice.",proof:"Arrange one complete song from lead sheet to performance chart, justify every bass role and register, and produce two versions whose different line choices preserve the same song identity."},
];

export const THEORY_DICTIONARIES:TheoryDictionary[]=[
 {id:"intervals",title:"Interval dictionary",intro:"Distance, sound and the fastest bass use. Compound intervals repeat the quality above the octave.",columns:["INTERVAL","FORMULA","BASS MEANING"],rows:[
  {name:"Perfect unison",formula:"0 SEMITONES · 1",semitones:0,meaning:"Home, doubling and exact pitch identity."},
  {name:"Minor 2nd",formula:"1 SEMITONE · ♭2",semitones:1,meaning:"Maximum local rub; leading motion or Phrygian color."},
  {name:"Major 2nd",formula:"2 SEMITONES · 2",semitones:2,meaning:"Stepwise connection, suspension or open modal color."},
  {name:"Minor 3rd",formula:"3 SEMITONES · ♭3",semitones:3,meaning:"Minor quality, blues color and compact melodic leap."},
  {name:"Major 3rd",formula:"4 SEMITONES · 3",semitones:4,meaning:"Major quality and essential guide tone."},
  {name:"Perfect 4th",formula:"5 SEMITONES · 4",semitones:5,meaning:"Strong suspension, quartal sound and standard string tuning."},
  {name:"Tritone",formula:"6 SEMITONES · ♯4/♭5",semitones:6,meaning:"Dominant pressure, altered color and symmetrical division."},
  {name:"Perfect 5th",formula:"7 SEMITONES · 5",semitones:7,meaning:"Stable support, power-chord clarity and strong root reinforcement."},
  {name:"Minor 6th",formula:"8 SEMITONES · ♭6",semitones:8,meaning:"Dark minor color; inversion of major 3rd."},
  {name:"Major 6th",formula:"9 SEMITONES · 6",semitones:9,meaning:"Dorian lift, major color and inversion of minor 3rd."},
  {name:"Minor 7th",formula:"10 SEMITONES · ♭7",semitones:10,meaning:"Dominant/minor-7 family, funk and Mixolydian color."},
  {name:"Major 7th",formula:"11 SEMITONES · 7",semitones:11,meaning:"Strong leading pull and major-7 color."},
  {name:"Octave",formula:"12 SEMITONES · 8",semitones:12,meaning:"Same pitch class, new register and classic bass-line reinforcement."},
 ]},
 {id:"chords",title:"Chord-formula dictionary",intro:"Spell from the chord root. Extensions are compound scale degrees; slash notes specify the bass.",columns:["CHORD","FORMULA","FUNCTION / COLOR"],rows:[
  {name:"Power chord",formula:"1 5 (8)",meaning:"No third, so neither major nor minor. The bass supplies the root and the guitar the fifth; whatever states the third decides the key."},{name:"Major triad",formula:"1 3 5",meaning:"Stable major quality."},{name:"Minor triad",formula:"1 ♭3 5",meaning:"Stable minor quality."},{name:"Diminished triad",formula:"1 ♭3 ♭5",meaning:"Unstable symmetrical tendency."},{name:"Augmented triad",formula:"1 3 ♯5",meaning:"Open symmetrical expansion."},
  {name:"Sus2 / Sus4",formula:"1 2 5 / 1 4 5",meaning:"Third removed; quality suspended."},{name:"Major 6",formula:"1 3 5 6",meaning:"Warm tonic major color."},{name:"Minor 6",formula:"1 ♭3 5 6",meaning:"Minor with bright internal tension."},{name:"Major 7",formula:"1 3 5 7",meaning:"Tonic major with leading-tone color."},
  {name:"Dominant 7",formula:"1 3 5 ♭7",meaning:"Dominant, blues or Mixolydian family."},{name:"Minor 7",formula:"1 ♭3 5 ♭7",meaning:"Minor, Dorian or Aeolian family."},{name:"Minor-major 7",formula:"1 ♭3 5 7",meaning:"Tense tonic minor and melodic-minor color."},{name:"Half-diminished 7",formula:"1 ♭3 ♭5 ♭7",meaning:"Minor-key predominant and Locrian family."},
  {name:"Diminished 7",formula:"1 ♭3 ♭5 𝄫7",meaning:"Symmetrical connector and leading-tone function."},{name:"Add9",formula:"1 3 5 9",meaning:"A ninth without the seventh. Written add9 precisely because a plain 9 would imply the seventh underneath it."},{name:"Major 9",formula:"1 3 5 7 9",meaning:"Expanded tonic major."},{name:"Major 6/9",formula:"1 3 5 6 9",meaning:"Tonic major with no seventh at all — the most settled way to end without a leading tone."},{name:"Dominant 9",formula:"1 3 5 ♭7 9",meaning:"Dominant with smoother upper color."},{name:"Minor 9",formula:"1 ♭3 5 ♭7 9",meaning:"Expanded minor/Dorian color."},
  {name:"11 / Sus dominant",formula:"1 5 ♭7 9 11",meaning:"Open dominant; third often omitted."},{name:"13",formula:"1 3 5 ♭7 9 13",meaning:"Dominant with major-sixth color; 11 often omitted."},{name:"Altered dominant",formula:"1 3 ♭7 + ♭9/♯9/♭5/♯5",meaning:"Directed maximum tension into a target."},{name:"Slash chord",formula:"CHORD / REQUIRED BASS",meaning:"Inversion, pedal or independent bass harmony."},
  {name:"Major 7 ♯11",formula:"1 3 ♯11 5 7",meaning:"The Lydian chord: a major seventh whose fourth is raised so it stops clashing with the third."},
  {name:"Major 7 ♯5",formula:"1 3 ♯5 7",meaning:"Major seventh over an augmented fifth; Lydian augmented is its home."},
  {name:"Minor 11",formula:"1 ♭3 5 ♭7 9 11",meaning:"Minor seventh carrying both upper tensions; the eleventh sits comfortably here in a way it never does over a major third."},
  {name:"Dominant 7sus4",formula:"1 4 5 ♭7",meaning:"A dominant that withholds its third, so the pull is present but unresolved until the fourth steps down."},
  {name:"Minor 6/9",formula:"1 ♭3 5 6 9",meaning:"Tonic minor with a natural sixth rather than a flat seventh — the melodic-minor sound of a minor chord at rest."},
 ]},
 {id:"scales",title:"Scale and collection dictionary",intro:"Formula is measured from one tonic. Hear the identity before memorizing a fingering.",columns:["COLLECTION","FORMULA","PRIMARY SOUND / USE"],rows:[
  {name:"Major / Ionian",formula:"1 2 3 4 5 6 7",meaning:"Major key reference and tonic harmony."},{name:"Natural minor / Aeolian",formula:"1 2 ♭3 4 5 ♭6 ♭7",meaning:"Natural minor key collection."},{name:"Harmonic minor",formula:"1 2 ♭3 4 5 ♭6 7",meaning:"Minor with strong dominant–tonic pull."},{name:"Melodic minor",formula:"1 2 ♭3 4 5 6 7",meaning:"Modern minor color and altered-mode parent."},
  {name:"Major pentatonic",formula:"1 2 3 5 6",meaning:"Open major groove and melody language."},{name:"Minor pentatonic",formula:"1 ♭3 4 5 ♭7",meaning:"Portable minor, rock, funk and blues vocabulary."},{name:"Blues",formula:"1 ♭3 4 ♭5 5 ♭7",meaning:"Minor pentatonic with expressive blue motion."},{name:"Dorian",formula:"1 2 ♭3 4 5 6 ♭7",meaning:"Minor with natural-six lift."},
  {name:"Phrygian",formula:"1 ♭2 ♭3 4 5 ♭6 ♭7",meaning:"Minor with exposed flat-two root rub."},{name:"Lydian",formula:"1 2 3 ♯4 5 6 7",meaning:"Major with raised-four openness."},{name:"Mixolydian",formula:"1 2 3 4 5 6 ♭7",meaning:"Major dominant, rock and funk color."},{name:"Locrian",formula:"1 ♭2 ♭3 4 ♭5 ♭6 ♭7",meaning:"Half-diminished environment with unstable tonic fifth."},
  {name:"Chromatic",formula:"1 ♭2 2 ♭3 3 4 ♯4 5 ♭6 6 ♭7 7",meaning:"Complete pitch field; requires contextual hierarchy."},{name:"Whole tone",formula:"1 2 3 ♯4 ♯5 ♭7",meaning:"Symmetrical augmented-dominant color."},{name:"Half–whole diminished",formula:"1 ♭9 ♯9 3 ♯11 5 13 ♭7",meaning:"Dominant ♭9/♯9/♯11/13 tension."},{name:"Whole–half diminished",formula:"1 2 ♭3 4 ♭5 ♭6 𝄫7 7",meaning:"Fully diminished chord environment."},
  {name:"Altered / super-Locrian",formula:"1 ♭9 ♯9 3 ♭5 ♭13 ♭7",meaning:"Seventh mode of melodic minor: every tension a dominant can carry, and no natural fifth to steady it."},
  {name:"Harmonic major",formula:"1 2 3 4 5 ♭6 7",meaning:"Major with a borrowed flat-six, which is where a ♭13 over a major-seventh sound comes from."},
  {name:"Dominant bebop",formula:"1 2 3 4 5 6 ♭7 7",meaning:"Mixolydian plus a passing natural seven, so chord tones keep landing on the beat through a bar of eighths."},
  {name:"Dorian ♭2",formula:"1 ♭2 ♭3 4 5 6 ♭7",meaning:"Second mode of melodic minor: Dorian with a flattened second, where the sus and minor colours meet."},
  {name:"Lydian augmented",formula:"1 2 3 ♯4 ♯5 6 7",meaning:"Third mode of melodic minor: raised fourth and fifth together, which is where maj7♯5 lives."},
  {name:"Lydian dominant",formula:"1 2 3 ♯4 5 6 ♭7",meaning:"Fourth mode of melodic minor: Mixolydian with a raised fourth — a dominant that does not want to resolve."},
  {name:"Mixolydian ♭6",formula:"1 2 3 4 5 ♭6 ♭7",meaning:"Fifth mode of melodic minor: a dominant carrying ♭13 while its ninth and fifth stay natural."},
  {name:"Locrian natural 2",formula:"1 2 ♭3 4 ♭5 ♭6 ♭7",meaning:"Sixth mode of melodic minor: Locrian with the second restored, which is what makes iiø singable."},
  {name:"Phrygian dominant",formula:"1 ♭2 3 4 5 ♭6 ♭7",meaning:"Fifth mode of harmonic minor: a major third over a flat second, and the V of a minor key."},
 ]},
 {id:"function",title:"Harmonic-function dictionary",intro:"The bassist makes function audible through root, inversion, duration and destination.",columns:["FUNCTION / MOVE","TYPICAL SYMBOL","WHAT THE EAR EXPECTS"],rows:[
  {name:"Tonic",formula:"I / i · vi / iii substitutes",meaning:"Rest, identity and return."},{name:"Predominant",formula:"ii / IV · iiø / iv",meaning:"Departure and preparation for dominant."},{name:"Dominant",formula:"V7 / vii°",meaning:"Directed instability and demand for tonic."},{name:"Authentic cadence",formula:"V–I / V–i",meaning:"Strong tonal closure, strongest with bass 5→1."},
  {name:"Plagal cadence",formula:"IV–I / iv–i",meaning:"Subdominant-colored closure."},{name:"Deceptive cadence",formula:"V–vi / V–♭VI",meaning:"Expected tonic denied but voice leading continues."},{name:"Secondary dominant",formula:"V/x → x",meaning:"Temporary emphasis of a non-tonic target."},{name:"Tritone substitution",formula:"♭II7 → I",meaning:"Chromatic bass resolution with shared guide-tone tritone."},
  {name:"Backdoor dominant",formula:"♭VII7 → I",meaning:"Borrowed/plagal-flavored dominant arrival."},{name:"Modal mixture",formula:"BORROW FROM PARALLEL",meaning:"Same tonic, altered modal color."},{name:"Pedal point",formula:"FIXED BASS UNDER CHANGES",meaning:"One centre or tension reference beneath moving harmony."},{name:"Modulation",formula:"NEW FUNCTION + CADENCE",meaning:"A new tonic takes structural control."},
 ]},
 {id:"rhythm",title:"Rhythm, meter and form dictionary",intro:"Terms that tell the bassist how time is grouped, displaced and navigated.",columns:["TERM","SHORTHAND","PRACTICAL MEANING"],rows:[
  {name:"Pulse",formula:"REFERENCE BEAT",meaning:"Recurring time point the body predicts."},{name:"Subdivision",formula:"BEAT → EQUAL PARTS",meaning:"Internal grid for attacks and rests."},{name:"Simple meter",formula:"BEAT DIVIDES BY 2",meaning:"2/4, 3/4 and 4/4 families."},{name:"Compound meter",formula:"BEAT DIVIDES BY 3",meaning:"6/8, 9/8 and 12/8 families."},
  {name:"Syncopation",formula:"WEIGHT OFF EXPECTED BEAT",meaning:"Offbeat attack, anticipation or tie across weight."},{name:"Tuplet",formula:"n NOTES IN ANOTHER VALUE",meaning:"Alternative equal division of a span."},{name:"Polyrhythm",formula:"DIFFERENT DIVISIONS, SAME SPAN",meaning:"Two rhythmic grids sounding together."},{name:"Polymeter",formula:"DIFFERENT BAR CYCLES",meaning:"Same tempo, independently repeating meters."},
  {name:"Metric modulation",formula:"OLD SUBDIVISION = NEW BEAT",meaning:"Related but newly defined tempo."},{name:"Harmonic rhythm",formula:"RATE OF CHORD CHANGE",meaning:"How quickly harmony moves, independent of BPM."},{name:"Pickup / anticipation",formula:"BEFORE BAR OR CHANGE",meaning:"Phrase or harmony begins early."},{name:"Tag / vamp / coda",formula:"REPEAT / HOLD / FINAL ROUTE",meaning:"Extend, wait or navigate the ending."},
 ]},
 {id:"terms",title:"Naming and terminology",intro:"The same thing under two names. This site uses American terms — quarter note, half step, measure — because most of what you will read online does; these are what the rest of the world calls them, and you will meet both.",columns:["AS USED HERE","ALSO CALLED","WHAT IT IS"],rows:[
  {name:"Whole note",formula:"Semibreve",meaning:"Four beats in 4/4. The longest value in common use."},
  {name:"Half note",formula:"Minim",meaning:"Two beats in 4/4."},
  {name:"Quarter note",formula:"Crotchet",meaning:"One beat in 4/4. The value a metronome click usually represents."},
  {name:"Eighth note",formula:"Quaver",meaning:"Half a beat. Two per click, and the unit most grooves are felt in."},
  {name:"16th note",formula:"Semiquaver",meaning:"A quarter of a beat. Four per click; the unit of funk and most bass subdivision."},
  {name:"32nd note",formula:"Demisemiquaver",meaning:"An eighth of a beat. Rare on bass outside fills and written flourishes."},
  {name:"Dotted note",formula:"Dotted note",meaning:"A dot adds half the value again: a dotted quarter is a beat and a half."},
  {name:"Half step",formula:"Semitone",meaning:"One fret. The smallest distance in the system this site teaches."},
  {name:"Whole step",formula:"Tone",meaning:"Two frets. Two half steps."},
  {name:"Measure",formula:"Bar",meaning:"One group of beats between barlines."},
  {name:"Staff",formula:"Stave",meaning:"The five lines notes are written on."},
  {name:"Ledger line",formula:"Leger line",meaning:"A short line extending the staff for notes above or below it."},
  {name:"Accidental",formula:"Accidental",meaning:"A ♯, ♭ or ♮ altering a pitch for the rest of the bar."},
  {name:"Tie",formula:"Tie",meaning:"Joins two notes of the same pitch into one longer sound. A slur joins different pitches and means play them smoothly."},
  {name:"Natural sign",formula:"Natural",meaning:"♮ cancels a sharp or flat, whether it came from the key signature or earlier in the bar."},
  {name:"Enharmonic",formula:"Enharmonic",meaning:"Two names for one pitch. F♯ and G♭ are the same fret, and which you write depends on where the music is going."},
  {name:"B♭ / B",formula:"B / H",meaning:"German notation calls B♭ “B” and B natural “H”. It appears in classical scores and in some European chord charts."},
  {name:"Note letters",formula:"Movable do",meaning:"Letters name fixed pitches; movable-do solfège names degrees, so “do” is whatever the tonic is. Fixed-do treats do as C always."},
  {name:"Nashville numbers",formula:"Roman numerals",meaning:"Both number the chords of a key. Nashville uses plain digits on charts; Roman numerals carry quality in their case and symbols."},
  {name:"Tab",formula:"Tablature",meaning:"Which string and fret, rather than which pitch. It answers the fingering and says nothing about duration unless rhythm is written above it."},
 ]},];
